export const keywords = [
  "Kartik Maheshwari",
  "Kartik",
  "Maheshwari",
  "Kartik23411", // GitHub username
  "localhost:3000", // Portfolio URL
  "contact.mkartik@gmail.com", // Email for search
  "linkedin/in/kartik411", // LinkedIn profile
  "Kartik Maheshwari portfolio",
  "Kartik Maheshwari developer",
  "Kartik Maheshwari software engineer",
  "Kartik Maheshwari web developer",
  "Kartik Maheshwari AI developer",
  "Kartik Maheshwari full-stack developer",
  "Kartik Maheshwari projects",
  "Kartik Maheshwari resume",
  "Kartik Maheshwari contact",

  "software Engineer portfolio",
  "software developer India",
  "software developer Rajasthan",
  "full-stack engineer portfolio",
  "open source mobile developer",
  "mobile developer portfolio",
  "android developer personal site",
  "network engineer portfolio",
  "ai Research portfolio",
  "machine Learning Engineer",
  "tech Enthusiast",
  "native Android developer",
  "coding question developer",
  "technical question curator",
  "data bug resolution",
  "ai Enthusiast",
  "machine learning enthusiast",
  "entry-level software engineer",
  "junior mobile developer",

  "C programming",
  "C++ programming",
  "Java developer",
  "Kotlin developer",
  "Python Programming",
  "Android developer",
  "Mobile developer",
  "Python developer",
  "Kotlin Developer",

  "BERT model",
  "Machine Learning",
  "Deep Learning",
  "Generative AI",
  "Large Language Models (LLMs)",
  "LLaMA language model",
  "LangChain developer",
  "Gemini API integration",
  "Hugging Face API for AI",
  "Ollama local LLM",
  "Natural Language Processing (NLP)",
  "Computer Vision",
  "Prompt Engineering",
  "AI model fine-tuning",
  "TensorFlow",
  "PyTorch",
  "Keras",

  "Git version control",
  "GitHub collaboration",
  "Firebase hosting",
  "Vercel deployment",
  "Docker developer",
  "Kubernetes basics",
  "CI/CD with GitHub Actions",
  "VS Code extensions",
  "Framer",
  "Figma UI/UX design",

  "HackerRank Problem Solving Certificate",
  "Scientific Computing with Python FreeCodeCamp",
  "Software Development Trainee AMCAT",
  "Data Processing Specialist AMCAT",
  "Business Analyst Certificate AMCAT",

  "best student portfolios 2025",
  "modern software devloper portfolio",
  "best open source portfolio projects",
  "personal developer site",
  "tech blog and portfolio",
  "build portfolio with Tailwind CSS",
  "interactive resume website",
  "coding portfolio examples",
  "developer with AI projects",
  "best portfolio with AI features",
  "free tools for developers",
  "developer website inspiration",
  "SEO optimized portfolio site",
  "how to build a developer portfolio",
  "showcase coding projects",
  "web development trends 2025",
  "computer science student projects",
  "B.Tech Computer Science portfolio",
  "RTU student developer",
  "hire software developer",
  "freelance software developer",
  "internship software development",
  "student developer looking for job",

  "JavaScript",
  "Kotlin",
  "HTML",
  "CSS",
  "CNN",
  "React",
  "Tailwind",
  "Framer Motion",
  "PostgreSQL",
  "MongoDB",
  "Supabase",
  "MySQL",
  "Vercel",
  "LLM",
  "Ollama",
  "GitHub Actions",
  "responsive UI",
  "dark mode toggle",
  "UI/UX",
  "AI",
  "Machine Learning",
  "Deep Learning",
  "LSTM",
  "LLaMA",
  "Firebase",
  "REST API",
  "WebSockets",
  "Git",
  "GitHub",
  "VS Code",
  "Node.js",
  "Express.js",
  "Python",
  "C",
  "C++",
  "Java",
  "Data Structures and Algorithms",
  "DSA",
  "Object-Oriented Programming",
  "OOP",
  "Functional Programming",
  "System Design",
  "Agile development",
  "Clean Code",
  "Scalable architecture",
  "MVC Architecture",
  "MVi Architecture",
  "MVVM Architecture",
  "Android Sdk",
  "Network Engineer",
  "Computer Network",
  "Tech Enthusiast",
  "ML Engineer",
];
